note_taker/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('auth/', include('users.urls')),
]

note_taker/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', views.fetch_notes, name='fetch_notes'),
    path('add/note/', views.create_note, name='create_note'),
    path('note/<int:note_id>/', views.note_detail, name='note_detail'),
    path('edit/note/<int:note_id>/', views.edit_note, name='edit_note'),
    path('confirm/delete/<int:note_id>/', views.confirm_delete, name='confirm_delete'),
    path('delete/note/<int:note_id>/', views.delete_note, name='delete_note'),
]

note_taker/users/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "users"

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('log-in/', LoginView.as_view(template_name="users/log-in.html"), name="log_in"),
    path('log-out/', LogoutView.as_view(), name="log_out"),
]

note_taker/notes/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.TextChoices):
    WORK = "WK", "Work"
    PERSONAL = "PSNL", "Personal"
    IDEAS = "IDE", "Ideas"

# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.CharField(choices=Category.choices, max_length=4, default=Category.PERSONAL)
    date_created = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)


note_taker/users/models.py
from django.db import models

# Create your models here.

note_taker/notes/forms.py
from django import forms

from .models import Note, Category

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["title", "content", "category"]


class SearchNotesForm(forms.Form):
    title = forms.CharField(max_length=255, required=False)

class FilterByCategory(forms.Form):
    category = forms.ChoiceField(choices=Category.choices, required=False)

note_taker/notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Note
from .forms import NoteForm, SearchNotesForm, FilterByCategory

# Create your views here.

def home(request):
    return render(request, "notes/home.html")

@login_required
def fetch_notes(request):
    notes = Note.objects.filter(added_by=request.user)
    search_form = SearchNotesForm(request.GET)

    if search_form.is_valid():
        title = search_form.cleaned_data.get('title')
        if title:
            notes = notes.filter(title__icontains=title)

    filter_form = FilterByCategory(request.GET)

    if filter_form.is_valid():
        category = filter_form.cleaned_data.get('category')
        if category:
            notes = notes.filter(category=category)

    context = {
        "notes": notes,
        "filter_form": filter_form,
    }
    return render(request, "notes/notes.html", context)


@login_required
def note_detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to view that note")
        return redirect("notes:home")
    return render(request, "notes/note.html", {"note": note})


@login_required
def create_note(request):
    form = NoteForm()

    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.added_by = request.user
            note.save()
            return redirect('notes:fetch_notes')

    context = {
        "form": form
    }
    return render(request, "notes/create-note.html", context)


@login_required
def edit_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to edit that note")
        return redirect("notes:home")
    
    form = NoteForm(instance=note)

    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect(reverse('notes:note_detail', kwargs={"note_id": note_id}))

    context = {
        "form": form,
        "note": note,
    }
    return render(request, "notes/edit-note.html", context)

@login_required
def confirm_delete(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to delete that note")
        return redirect("notes:home")
    
    return render(request, "notes/confirm-delete.html", {"note": note})

@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to delete that note")
        return redirect("notes:home")
    

    if request.method == "POST":
        note.delete()
        return redirect("notes:fetch_notes")

    return HttpResponseNotAllowed(["POST"])

note_taker/users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.
def sign_up(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully")
            return redirect("users:log_in")

    context = {"form": form}
    return render(request, "users/sign-up.html", context)

note_taker/templates/notes/confirm-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm {{ note.title }} delete</title>
</head>
<body>
    <h3>Are you sure you want to delete your note titled "{{ note.title }}"?</h3>
    <div>Content:
        <div>{{ note.content }}</div>
        <p>{{ note.get_category_display }}</p>
    </div>
    <form action="{% url 'notes:delete_note' note.id %}" method="POST">
        {% csrf_token %}
        <button type="submit">Yes I'm sure</button>
    </form>

    <a href="{% url 'notes:note_detail' note.id %}">No, take me back</a>
</body>
</html>

note_taker/templates/notes/create-note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Note</title>
</head>
<body>
    <h3>Add Note</h3>
    <form action="{% url 'notes:create_note' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Note</button>
    </form>
</body>
</html>

note_taker/templates/notes/edit-note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit {{ note.title }}</title>
</head>
<body>
    <h3>Edit {{ note.title }}</h3>
    <form action="{% url 'notes:edit_note' note.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Edit Note</button>
    </form>
</body>
</html>

note_taker/templates/notes/home.html
{% extends "partials/base.html" %}

{% block title %}
Note Taker
{% endblock title %}

{% block body %}
<h1>Welcome to our Note Taker App</h1>

<div>
    <a href="{% url 'notes:fetch_notes' %}">View Your Notes</a>
</div>
{% endblock body %}

note_taker/templates/notes/note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ note.title }}</title>
</head>
<body>

    <div>
        <h3>{{ note.title }}</h3>
        <div>{{ note.content }}</div>
        <p>Category: {{ note.get_category_display }}</p>
    </div>

    <div>
        <a href="{% url 'notes:edit_note' note.id %}">Edit</a>
        <a href="{% url 'notes:confirm_delete' note.id %}">Delete</a>
    </div>

</body>
</html>

note_taker/templates/notes/notes.html
{% extends "partials/base.html" %}

{% block title %}
Notes
{% endblock title %}

{% block body %}

    <a href="{% url 'notes:create_note' %}">Add Note</a>

    <div>
        <form action="{% url 'notes:fetch_notes' %}" method="GET">
            <input type="text" name="title">
            <button type="submit">Search</button>
        </form>
    </div>

    <div>
        <form action="{% url 'notes:fetch_notes' %}" method="GET">
             <select name="category">
            {% for value, label in filter_form.category.field.choices %}
                <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
            </select>
            {% comment %} {{ filter_form.as_p }} {% endcomment %}
            <button type="submit">Filter</button>
        </form>
    </div>

    <div>
        {% for note in notes %}
        <p><a href="{% url 'notes:note_detail' note.pk %}">{{ note.title }}</a></p>
        {% endfor %}
    </div>
{% endblock body %}