lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include("library.urls")),
    path('authors/', include("authors.urls")),
    path('dtl/', include("dtl.urls")),
    path('pages/', include("pages.urls")),
]

lms/dtl/urls.py
from django.urls import path

from . import views

app_name = "dtl"

urlpatterns = [
    path("", views.dtl_syntax, name="dtl_syntax"),
    path("cart/", views.cart, name="cart"),
]

lms/library/urls.py
from django.urls import path

from . import views

app_name = 'library'

urlpatterns = [
    path('all-authors/', views.all_authors, name='authors'),
    path('all-books/', views.all_books, name='all_books'),
    path('book-signings/', views.book_signings, name='book_signings'),
    path('add-book-no-django-form/', views.add_book_no_django_form, name="add_book_no_django_form"),
    path('add-book-with-django-form/', views.add_book_with_django_form, name="add_book_with_django_form"),
    path('add-book-with-django-form-manual-render/', views.add_book_with_django_form_manual_render, name="add_book_with_django_form_manual_render"),
    path('add-book-with-django-forms-dot-form/', views.add_book_with_django_forms_dot_form, name="add_book_with_django_forms_dot_form"),
    path('update-book-with-model-form/<int:book_id>/', views.update_book_with_model_form, name="update_book_with_model_form"),
    path('update-book-with-forms-dot-form/<int:book_id>/', views.update_book_with_forms_dot_form, name="update_book_with_forms_dot_form"),
    path('book/<int:book_pk>/', views.book_detail, name="book_detail"),
    path('confirm-delete/<int:book_pk>/', views.confirm_delete, name="confirm_delete"),
    path('delete-book/<int:book_id>/', views.delete_book, name="delete_book"),
]

lms/library/models.py
from django.db import models

from django.core.validators import MinLengthValidator

from authors.models import Author


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255, validators=[MinLengthValidator(2)])
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="books")
    number_of_pages = models.PositiveIntegerField()
    published_on = models.DateField()
    cover_image = models.ImageField(upload_to="book_covers/", blank=True, null=True)

    def __str__(self):
        return f"{self.title} by {self.author}"

lms/library/forms.py
from django import forms

from .models import Book
from authors.models import Author

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "number_of_pages", "published_on", "cover_image"]


class BookManualForm(forms.Form):
    title = forms.CharField(max_length=255, widget=forms.TextInput())
    author = forms.ModelChoiceField(queryset=Author.objects.all())
    number_of_pages = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 1}))
    # published_on = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    published_on = forms.DateField(widget=forms.SelectDateWidget())
    cover_image = forms.ImageField(required=False, widget=forms.ClearableFileInput())

lms/library/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse


from authors.models import Author
from .models import Book
from .forms import BookForm, BookManualForm

# Create your views here.
def all_authors(request):
    return render(request, "library/all-authors.html")


def book_signings(request):
    return render(request, "library/book-signings.html")


def all_books(request):
    all_books = Book.objects.all()
    return render(request, "library/all-books.html", {"books": all_books})


def add_book_no_django_form(request):
    all_authors = Author.objects.all()

    context = {
        "authors": all_authors
    }
    if request.method == "POST":
        title = request.POST.get('title')
        author_id = request.POST.get('author')
        no_of_pages = request.POST.get('number_of_pages')
        published_on = request.POST.get('published_on')
        cover_image = request.FILES.get('cover_image')

        author = Author.objects.get(id=author_id)
        print(author_id)

        Book.objects.create(title=title, author=author, number_of_pages=no_of_pages, published_on=published_on, cover_image=cover_image)
        return redirect('library:all_books')

    return render(request, "library/manual-form-create-book.html", context)


def add_book_with_django_form(request):
    form = BookForm()

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('library:all_books')

    context = {
        "form": form
    }
    return render(request, "library/auto-form-create-book copy.html", context)


def add_book_with_django_form_manual_render(request):
    form = BookForm()
    all_authors = Author.objects.all()


    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('library:all_books')

    context = {
        "form": form,
        "authors": all_authors,
    }
    return render(request, "library/manual-form-plus-django-form.html", context)


def add_book_with_django_forms_dot_form(request):
    form = BookManualForm()

    if request.method == "POST":
        form = BookManualForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            title = cleaned_data.get('title')
            author = cleaned_data.get('author')
            number_of_pages = cleaned_data.get('number_of_pages')
            published_on = cleaned_data.get('published_on')
            cover_image = cleaned_data.get('cover_image')
            Book.objects.create(title=title, author=author, number_of_pages=number_of_pages, published_on=published_on, cover_image=cover_image)
            return redirect('library:all_books')

    context = {
        "form": form
    }
    return render(request, "library/add-book-with-django-forms-dot-form.html", context)



def book_detail(request, book_pk):
    book = get_object_or_404(Book, pk=book_pk)
    return render(request, "library/book-detail.html", {"book": book})

def update_book_with_model_form(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = BookForm(instance=book)

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect(reverse('library:book_detail', kwargs={'book_pk': book_id}))

    context = {
        "form": form,
        "book": book,
    
    }
    
    return render(request, "library/update-book-with-model-form.html", context)


def update_book_with_forms_dot_form(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = BookManualForm(initial={
        'title': book.title,
        'author': book.author,
        'number_of_pages': book.number_of_pages,
        'published_on': book.published_on,
        'cover_image': book.cover_image
    })

    if request.method == "POST":
        form = BookManualForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            book.title = cleaned_data.get('title')
            book.author = cleaned_data.get('author')
            book.number_of_pages = cleaned_data.get('number_of_pages')
            book.published_on = cleaned_data.get('published_on')
            book.cover_image = cleaned_data.get('cover_image')
            book.save()
            return redirect(reverse('library:book_detail', kwargs={'book_pk': book_id}))

    context = {
        'form': form,
        'book': book,
    }
    return render(request, "library/update-book-with-forms-dot-form.html", context)


def confirm_delete(request, book_pk):
    book = get_object_or_404(Book, pk=book_pk)
    return render(request, "library/confirm-book-delete.html", {"book": book})


def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        book.delete()
        return redirect('library:all_books')
    
    return redirect(reverse('library:book_detail', kwargs={'book_pk': book_id}))

lms/templates/library/add-book-with-django-forms-dot-form.html
{% extends "partials/base.html" %}

{% block title %}Add a Book{% endblock title %}


{% block body %}
    <h1>Add a Book</h1>

    <form action="{% url 'library:add_book_with_django_forms_dot_form' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Submit</button>

    </form>

{% endblock body %}

lms/templates/library/all-authors.html
{% extends "partials/base.html" %}

{% block title %}All Authors{% endblock title %}


{% block body %}
    <h1>List of authors</h1>
{% endblock body %}

lms/templates/library/all-books.html
{% extends "partials/base.html" %}

{% block title %}All Books{% endblock title %}


{% block body %}
    <h1>List of Books</h1>
    <ul>
        {% for book in books %}
            <li><a href="{% url 'library:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock body %}

lms/templates/library/auto-form-create-book copy.html
{% extends "partials/base.html" %}

{% block title %}Add a Book{% endblock title %}


{% block body %}
    <h1>Add a Book</h1>

    <form action="{% url 'library:add_book_with_django_form' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_div }}

        <button type="submit">Submit</button>

    </form>

{% endblock body %}

lms/templates/library/book-detail.html
{% extends "partials/base.html" %}

{% block title %}{{ book.title }}{% endblock title %}


{% block body %}

    {% if book.cover_image  %}
        <img src="{{ book.cover_image.url }}" alt="Cover Image of {{ book.title }}">    
    {% endif %}

    <h1>{{ book.title }}</h1>

    <h3>{{ book.author.first_name }} {{ book.author.last_name }}</h3>
    <p>Number of Pages: {{ book.number_of_pages }}</p>
    <p>Published on: {{ book.published_on }}</p>

    <a href="{% url 'library:update_book_with_model_form' book.pk %}">Edit with ModelForm</a>
    <a href="{% url 'library:update_book_with_forms_dot_form' book.pk %}">Edit with forms.Form</a>

    <a href="{% url 'library:confirm_delete' book.pk %}">Delete</a>

{% endblock body %}

lms/templates/library/book-signings.html
{% extends "partials/base.html" %}

{% block title %}Book Signings{% endblock title %}


{% block body %}
    <h1>Upcoming Book Signings</h1>
{% endblock body %}

lms/templates/library/confirm-book-delete.html
{% extends "partials/base.html" %}

{% block title %}Confirm Delete {{ book.title }}{% endblock title %}


{% block body %}

    <div>
        <div>Are you sure you want to delete "{{ book.title }}"?</div>
        <form action="{% url 'library:delete_book' book.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit">Yes, I'm sure</button>
        </form>
        <a href="{% url 'library:book_detail' book.pk %}">No, take me back</a>
    </div>

{% endblock body %}

lms/templates/library/manual-form-create-book.html
{% extends "partials/base.html" %}

{% block title %}Add a Book{% endblock title %}


{% block body %}
    <h1>Add a Book</h1>

    <form action="{% url 'library:add_book_no_django_form' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="title">Title:</label>
            <input type="text" name="title" value="" required>
        </div>

        <div>
            <label for="author">Author:</label>
            <select name="author" required>
            {% for author in authors %}
                <option value="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</option>
            {% endfor %}
            </select>
        </div>

        <div>
            <label for="number_of_pages">Number of Pages:</label>
            <input type="number" name="number_of_pages" value="" required>
        </div>


        <div>
            <label for="published_on">Publication Date:</label>
            <input type="date" name="published_on" required>
        </div>

        <div>
            <label for="cover_image">Cover Image</label>
            <input type="file" name="cover_image" required>
        </div>

        <button type="submit">Submit</button>

    </form>

{% endblock body %}

lms/templates/library/manual-form-plus-django-form.html
{% extends "partials/base.html" %}

{% block title %}Add a Book{% endblock title %}


{% block body %}
    <h1>Add a Book</h1>

    <form action="{% url 'library:add_book_with_django_form_manual_render' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <ul>
            {% for error in form.non_field_errors %}
                <li class="li-error">{{ error }}</li>
            {% endfor %}
            </ul>
        {% endif %}

        <div>
            {% for error in form.title.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="title">Title:</label>
            <input type="text" name="title" {% if form.title.value %}value="{{ form.title.value }}"{% endif %} required>
        </div>

        <div>
            {% for error in form.author.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="author">Author:</label>
            <select name="author" required>
            {% for author in authors %}
                <option {% if author.id|slugify == form.author.value %}selected{% endif %} value="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</option>
            {% endfor %}
            </select>
        </div>

        <div>
            {% for error in form.number_of_pages.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="number_of_pages">Number of Pages:</label>
            <input type="number" name="number_of_pages" value="{{ form.number_of_pages.value|default_if_none:'' }}" required>
        </div>


        <div>
            {% for error in form.published_on.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="published_on">Publication Date:</label>
            <input type="date" name="published_on" required value="{{ form.published_on.value|default_if_none:'' }}">
        </div>

        <div>
            {% for error in form.cover_image.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="cover_image">Cover Image</label>
            <input type="file" name="cover_image" required>
        </div>

        <button type="submit">Submit</button>

    </form>

{% endblock body %}

lms/templates/library/update-book-with-forms-dot-form.html
{% extends "partials/base.html" %}

{% block title %}Update {{ book.title }}{% endblock title %}


{% block body %}
    <h1>Update {{ book.title }}</h1>

    <form action="{% url 'library:update_book_with_forms_dot_form' book.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <ul>
            {% for error in form.non_field_errors %}
                <li class="li-error">{{ error }}</li>
            {% endfor %}
            </ul>
        {% endif %}

        <div>
            {% for error in form.title.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="title">Title:</label>
            <input type="text" name="title" {% if form.title.value %}value="{{ form.title.value }}"{% endif %} required>
        </div>

        <div>
            {% for error in form.author.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="author">Author:</label>
            <select name="author" required>
            {% for author in form.fields.author.queryset %}
                <option {% if author.id|slugify == form.author.value %}selected{% endif %} value="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</option>
            {% endfor %}
            </select>
        </div>

        <div>
            {% for error in form.number_of_pages.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="number_of_pages">Number of Pages:</label>
            <input type="number" name="number_of_pages" value="{{ form.number_of_pages.value|default_if_none:'' }}" required>
        </div>


        <div>
            {% for error in form.published_on.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="published_on">Publication Date:</label>
            <input type="date" name="published_on" required value="{{ form.published_on.value|default_if_none:'' }}">
        </div>

        <div>
            {% for error in form.cover_image.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <label for="cover_image">Cover Image</label>
            <input type="file" name="cover_image" required>
        </div>

        <button type="submit">Submit</button>

    </form>

{% endblock body %}

lms/templates/library/update-book-with-model-form.html
{% extends "partials/base.html" %}

{% block title %}Update {{ book.title }}{% endblock title %}


{% block body %}
    <h1>Update {{ book.title }}</h1>

    <form action="{% url 'library:update_book_with_model_form' book.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_div }}

        <button type="submit">Submit</button>

    </form>

{% endblock body %}